---
sidebar: sidebar
permalink: task_dc_redhat_virtualization.html
keywords: data collector, Red Hat Virtualization
summary: Configuring Red Hat Virtualization data collector.
---

= Red Hat Virtualization data collector
:hardbreaks:

:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead] 
The DII data collector for Red Hat Virtualization also supports the open source project oVirt, and Oracle Linux Virtualization Manager. This data collector speaks REST API to the HTTPS interface on the management station 

== Terminology

For each asset type acquired by Data Infrastructure Insights, the most common terminology used for the asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term | Data Infrastructure Insights Term
|Disk|Virtual Disk
|Host|Host
|Virtual Machine|Virtual Machine
|Storage Domain|Data Store
|Logical Unit|LUN
|===
 
Note: These are common terminology mappings only and might not represent every case for this data collector.

== Requirements

* IP address/hostname of the RHV/oVirt/OLVM server over port 443 via REST API 
* Read-only username and password 
* RHV Version 3.0+/Ovirt 4.0+/OLVM 4.0+  

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|RHV/Ovirt/OLVM Server IP Address|IP address of the management station
|User name |User name 
|Password |Password
|===

== Advanced configuration 

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|HTTPS Communication Port|Port used for HTTPS communication to RHEV
|Inventory poll interval (min)|The default is 20 minutes.
//|Connection Timeout (sec)|The default is 60. 
|VM Performance|Enable performance collection
|Performance Poll Interval(sec)|The default is 900
|===

        
== Troubleshooting

Additional information on this Data Collector may be found from the link:concept_requesting_support.html[Support] page or in the link:reference_data_collector_support_matrix.html[Data Collector Support Matrix].

