---
sidebar: sidebar
permalink: task_dc_promox_ve.html
keywords: data collector, Promox VirtVirtual Environmentalization
summary: Configuring Promox Virtual Environment data collector.
---

= Red Hat OpenShift Virtualization data collector
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead] 
The DII Promox Virtual Environment collector will collect inventory data. This is an HTTPS REST API-based collector.

////
The authentication approach for this collector is an authentication token bound to a service account. To create both the user account and the token:

 oc create sa acq-readonly-cluster-user -n default
 oc adm policy add-cluster-role-to-user cluster-reader -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-user-binding
 oc adm policy add-cluster-role-to-user cluster-monitoring-view -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-monitor-user-binding

Run those 3 commands and watch for any errors. 

When the commands complete, run:

 oc create token acq-readonly-cluster-user --duration=8760h 

This will create a token bound to your user.
Note: It is recommended to set token duration. Be aware that Data collection will fail with a “Failed to connect” error following token expiration. 


Finally, you may also want your OSV administrator to run:

 oc cluster-info

This will return the hostname/IP address for management. Each DII OSV collector needs to be pointed at the IP/hostname for OSV management.
////

== Terminology

For each asset type acquired by Data Infrastructure Insights, the most common terminology used for the asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term | Data Infrastructure Insights Term
|Disk|Virtual Disk
|Host|Host
|Virtual Machine|Virtual Machine
|Storage Domain|Data Store
|Logical Unit|LUN
|===
 
Note: These are common terminology mappings only and might not represent every case for this data collector.



== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|Hostname or IP address|hostname IP address of the storage system 
|API Token ID| API tokern required for access
|API Token Secret| Secret for the above token
|===

== Advanced configuration 

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|HTTPS Communication Port|Port used for HTTPS communication (default 8006)
|Inventory poll interval (min)|The default is 20 minutes.

|===
        
== Troubleshooting

Additional information on this Data Collector may be found from the link:concept_requesting_support.html[Support] page or in the link:reference_data_collector_support_matrix.html[Data Collector Support Matrix].

