---
sidebar: sidebar
permalink: task_query_assign_multiple_applications.html
summary: Efficiently manage applications and annotations across multiple assets using query-based bulk operations to assign or remove them without manual, individual asset configuration.
keywords: query, queries, application, annotation, multiple
---

= Assigning multiple applications to or removing multiple applications from assets
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Streamline asset management by using queries to perform bulk operations on applications and annotations. Instead of manually configuring each asset individually, you can efficiently assign or remove multiple applications and annotations across groups of assets in a single operation. 

NOTE: You can use these steps to add or remove link:task_defining_annotations.html[annotations] in the same way.

.Before you begin

You must have already created a query that finds all the assets that you to edit.

.Steps
. Click *Explore* and select *Metric Queries*.
+
The Queries page displays.
. Click the name of the query that finds the assets.
+
The list of assets associated with the query displays.
. Select the desired assets in the list or click the top checkbox to select All.
+
The Bulk Actions drop-down displays.
.  To add an application to the selected assets, click Bulk Actions and select *Add Application*.
. Select one or more applications.
+
You can select multiple applications for hosts, internal volumes, qtrees, and virtual machines; however, you can select only one application for a volume or a share.
. Click *Save*.

. To remove an application assigned to the assets, click Bulk Actions and select *Remove Application*.
. Select the application or applications you want to remove.
. Click *Delete*.

Any new applications you assign override any applications on the asset that were derived from another asset. For example, volumes inherit applications from hosts, and when new applications are assigned to a volume, the new application takes precedence over the derived application.

After you click _Save_ on a bulk add or _Remove_ on a bulk delete action, Data Infrastructure Insights informs you that the action will take some time. You can dismiss this message; the action will continue in the background. 

NOTE: For environments with large amounts of related assets, inheritance of application assignments to those assets could take several minutes. Please allow more time for inheritance to occur if you have many related assets.



