---
sidebar: sidebar
permalink: task_cs_add_collector_ontap.html
keywords:  data collector, ONTAP, SVM
summary: Configure NetApp ONTAP data collectors to monitor file access, user activity, and detect security threats across your SVM infrastructure.
---

= Configuring the NetApp ONTAP Data Collector
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Enable comprehensive monitoring of your NetApp ONTAP storage by configuring data collectors that capture file and user access data for security threat detection. This guide provides step-by-step instructions to connect Workload Security agents to your SVMs and begin collecting data for real-time analysis. 


.Before you begin

You need the following information to configure this data collector:

* An agent must be configured to collect data
* The SVM management IP address
* A user name to access the SVM
* The password to access the SVM


.Steps for Configuration 

. Log in as Administrator or Account Owner to your Workload Security environment. 
. Click *Observability > Collectors > +Data Collectors* 
+
The system displays the available Data Collectors.

. Click *+Monitor* in the NetApp ONTAP tile. 
+ 
The system displays the Add Data Collector: Ontap SVM configuration page. 

. Enter a unique name for the collector
. Select the agent that will be collecting the data 
. Enter the SVM management IP address
. Enter the user name to access the SVM
. Enter the password to access the SVM
. Click *+Add Collector*

.After you finish

* Click *Workload Security > Collectors* to check the status of the collector you configured.
+
There is normally a delay before the collector status is displayed.


