---
sidebar: sidebar
permalink: task_config_cs_incloud.html
keywords:  Cloud, Storage, AWS, Cloud Volumes, Cloud ONTAP, firewall, VPC, Subnet,  cloud secure
summary: Set up Workload Security data collectors for Cloud Volumes ONTAP and Amazon FSx for NetApp ONTAP to monitor file access, user activity, and detect threats across your cloud storage infrastructure.
---

= Configuring the Cloud Volumes ONTAP and Amazon FSx for NetApp ONTAP collector 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Monitor file and user access across your cloud storage infrastructure by configuring Workload Security data collectors for Cloud Volumes ONTAP and Amazon FSx for NetApp ONTAP. This guide provides step-by-step instructions for deploying Agents in AWS and connecting them to your cloud storage instances.


== Cloud Volumes ONTAP Storage Configuration

See the OnCommand Cloud Volumes ONTAP Documentation to configure a single-node / HA AWS instance to host the Workload Security Agent: 
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html

After the configuration is complete, follow the steps to setup your SVM: 
https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html

== Supported Platforms

*	Cloud Volumes ONTAP, supported in all the available cloud service providers wherever available. For example: Amazon, Azure, Google Cloud.
*	ONTAP Amazon FSx


== Agent Machine Configuration

The agent machine must be configured in the respective subnets of the cloud Service providers. Read more about network access in the [Agent Requirements].

Below are the steps for Agent installation in AWS. Equivalent steps, as applicable to the cloud service provider, can be followed in Azure or Google Cloud for the installation.

In AWS, use the following steps to configure the machine to be used as a Workload Security Agent:


Use the following steps to configure the machine to be used as a Workload Security Agent:

.Steps

. Log in to the AWS console and navigate to EC2-Instances page and select _Launch instance_.

. Select a RHEL or CentOS AMI with the appropriate version as mentioned in this page: 
https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html

. Select the VPC and Subnet that the Cloud ONTAP instance resides in.

. Select _t2.xlarge_ (4 vcpus and 16 GB RAM) as allocated resources. 

.. Create the EC2 instance.

. Install the required Linux packages using the YUM package manager:  

.. Install _wget_ and _unzip_ native Linux packages.



== Install the Workload Security Agent

. Log in as Administrator or Account Owner to your Data Infrastructure Insights environment. 

. Navigate to Workload Security *Collectors* and click the *Agents* tab. 

. Click *+Agent* and specify RHEL as the target platform.

. Copy the Agent Installation command. 

. Paste the Agent Installation command into the RHEL EC2 instance you are logged in to.
This installs the Workload Security agent, providing all of the link:concept_cs_agent_requirements.html[Agent Prerequisites] are met. 

For detailed steps please refer to this link:
https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html#steps-to-install-agent



== Troubleshooting

Known problems and their resolutions are described in the following table.

|===
|Problem 	|Resolution
|“Workload Security: Failed to determine ONTAP type for Amazon FxSN data collector” error is shown by the Data Collector.
Customer is unable to add new Amazon FSxN data collector into Workload Security.  Connection to FSxN cluster on port 443 from the agent is timing out. Firewall and AWS security groups have the required rules enabled to allow communication. An agent is already deployed and is in the same AWS account as well. This same agent is used to connect and monitor the remaining NetApp devices (and all of them are working).	
|Solve this issue by adding fsxadmin LIF network segment to agent's security rule.
Allowed all ports if you are not sure about the ports.
|===








