---
sidebar: sidebar
permalink: task_query_copy_table_values.html
summary: Copy table values to the clipboard using text selection or one-click copying for efficient data transfer to search fields and external applications.
keywords: query, queries, copy, values, clipboard
---

= Copying table values
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Streamline your workflow by copying table values directly to the clipboard for use in searches or external applications. Choose between manual text selection or convenient one-click copying for single-value fields with asset links.

.About this task
There are two methods you can use to copy values from tables or query results to the clipboard.

.Steps
. Method 1: Highlight the desired text with the mouse, copy it, and paste it into search fields or other applications.
. Method 2: For single-value fields, hover over the field and click the clipboard icon that appears. The value is copied to the clipboard for use in search fields or other applications.
+
Note that only values that are links to assets can be copied using this method. Only fields that include single values (i.e. non-lists) have the copy icon.
