---
sidebar: sidebar
permalink: task_dc_promox_ve.html
keywords: data collector, Promox VirtVirtual Environmentalization
summary: Configuring Promox Virtual Environment data collector.
---

= Red Hat OpenShift Virtualization data collector
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead] 
The DII Promox Virtual Environment collector will collect inventory data. This is an HTTPS REST API-based collector.


== Terminology

For each asset type acquired by Data Infrastructure Insights, the most common terminology used for the asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols="50,50", options="header"]
|===
|Vendor/Model Term | Data Infrastructure Insights Term
|Disk|Virtual Disk
|Host|Host
|Virtual Machine|Virtual Machine
|Storage Domain|Data Store
|Logical Unit|LUN
|===
 
Note: These are common terminology mappings only and might not represent every case for this data collector.



== Configuration

[cols="50,50", options="header"]
|===
|Field | Description
|Hostname or IP address|hostname IP address of the storage system 
|API Token ID| API token required for access
|API Token Secret| Secret for the above token
|===

== Advanced configuration 

[cols="50,50", options="header"]
|===
|Field | Description
|HTTPS Communication Port|Port used for HTTPS communication (default 8006)
|Inventory poll interval (min)|The default is 20 minutes.

|===
        
== Troubleshooting

Additional information on this Data Collector may be found from the link:concept_requesting_support.html[Support] page or in the link:reference_data_collector_support_matrix.html[Data Collector Support Matrix].

