---
sidebar: sidebar
permalink: task_cloud_insights_onboarding_1.html
summary: Get started with Data Infrastructure Insights by signing up for a NetApp Console account and starting your free trial.
keywords: onboarding, new user, getting started
---

Getting Started: Sign Up and Start Your Free Trial
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Getting started with Data Infrastructure Insights is easy. Sign up for a NetApp Console account, create your site (sometimes called a "tenant"), and begin your free 30-day trial to explore all the features DII has to offer.


== Creating your NetApp Console account

To get started with NetApp's cloud services, go to link:https://console.netapp.com/[*NetApp Console*^] and click *Get Started*.

* If you have not already signed up, select *Sign Up*
* Enter a valid business email address and choose a password.
* Enter your company name, and your full name.
* Accept the terms and conditions and select *Continue*.

=== I already have a NetApp Console login

* Log in to https://services.cloud.netapp.com/fabric-view using your NetApp Console credentials. 
* Navigate to Products > Cloud Insights. 
* Select *Go to Data Infrastructure Insights*.


== Starting your Data Infrastructure Insights free trial

Under the Data Infrastructure Insights offering, click on *Start Free Trial*. DII will walk you through creating your company's site, including selecting the region where you want your site to reside. Your free 30-day trial starts when your tenant is created.

Once the creation of your site is complete, use your Console credentials to log in and explore the features DII has to offer.

During the free trial, you can link:concept_subscribing_to_cloud_insights.html[start your subscription] at any time. Once subscribed, you can enjoy uninterrupted access to DII features based on your current subscription plan.


== Sign in and go

Once your site has been created, you can log in to the NetApp Console Portal and navigate to the link:https://services.cloud.netapp.com[Cloud Services] page, then select *Go to Data Infrastructure Insights*. Your DII site opens in a new browser tab. 

NOTE: You must be logged in to NetApp Console before you can access NetApp Cloud Services.

Alternatively, you can open your Data Infrastructure Insights site URL directly in a browser:

 https://<site-prefix>.c01.cloudinsights.netapp.com/

The URL is also included in each user's invitation email for easy access and bookmarking. If you're not already logged in to Console, you'll be prompted to log in.

[NOTE]
====
New users must sign up for Console access before they can access their site URL.
====

The first time you log in to a new site, you'll be guided through steps to link:task_getting_started_with_cloud_insights.html[*begin gathering data*].

== Logging out

To log out of Data Infrastructure Insights, click your *User Name* and select *Log Out*.

