---
sidebar: sidebar
permalink: task_view_queries.html
summary: View and manage your saved queries with customizable display options including filtering, sorting, and column arrangement for efficient query organization and access.
keywords: query, queries, viewing
---

= Viewing queries
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Access and manage your saved queries through the query interface, where you can filter, sort, and customize the display to efficiently organize and locate the queries you need for asset monitoring and analysis.

.Steps
. Log in to your Data Infrastructure Insights tenant.
. Click *Explore* and select *All metric queries*.
You can change how queries display by doing any of the following:
. You can enter text in the filter box to search to display specific queries.
. You can change the sort order of the columns in the table of queries to either ascending (up arrow) or descending (down arrow) by clicking the arrow in the column header.
. To resize a column, hover the mouse over the column header until a blue bar appears. Place the mouse over the bar and drag it right or left.
. To move a column, click on the column header and drag it right or left.

When scrolling through the query results, be aware that the results may change as Data Infrastructure Insights automatically polls your data collectors. This may result in some items being missing, or some items appearing out of order depending on how they are sorted.
